language: python
python: 3.6

env:
  global:
    CC_TEST_REPORTER_ID=a252af86578cdb3eebca19c65c46844a04290dc50a52c1fa20092c964bbbfdc6 #noga

install: make

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter #noga
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make pytest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT